spring:
  application:
    name: bonienrichmentprototype
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value: true

server:
  port: 8081
  ssl:
    enabled: true            # can be set to false for http tests!
    client-auth: want

logging:
  config: logs/logback.xml
  level:
    org:
      springframework:
        security: info

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
    exposure:
      include: info
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
    caches:
      cache:
        time-to-live: 30s
  health:
    mongo:
      enabled: true

